spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employe
    username: isi
    password: isi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 2221
application:
  config:
    departement-url: http://localhost:8222/api/v1/departements
    post-url: http://localhost:8222/api/v1/posts
#    payement-url: http://localhost:8222/api/v1/payements
#    produit-url: http://localhost:8222/api/v1/produits