spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post
    username: isi
    password: isi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 2223