spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:1010/realms/micro-services"
  application:
    name: employe-service
  config:
    import: optional:configserver:http://localhost:8888
